### ISSUE TITLE
Archetype add noise to pom.xm

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-integrations#36]
when running the archetype like:

```
mvn archetype:generate \                 
 -DarchetypeGroupId=dev.knative.eventing \
 -DarchetypeArtifactId=kn-connector-archetype-sink \
 -DarchetypeVersion=1.0-SNAPSHOT \
 -DartifactId=aws-sns-sink \
 -Dkamelet-name=aws-sns \
 -Dcomponent-name=aws2-sns
```

the root `pom.xml` is updated with lots of noise. Like a new linefeed between each XML element / line in the pom file

**Comment by christophd** [comment]
yes, this is when running the `mvn archetype` command in the root directory of the project. I guess the Maven archetype tries to add the new module to the existing pom.xml and this causes the mess.

Can you please try to run this command in an empty sub-folder and the add the new module manually to the parent POM?

**Comment by matzew** [comment]
Inside an empty dir, e.g. `aws-sns-sink`, I am getting than this:

```
mvn archetype:generate \                 
 -DarchetypeGroupId=dev.knative.eventing \
 -DarchetypeArtifactId=kn-connector-archetype-sink \
 -DarchetypeVersion=1.0-SNAPSHOT \
 -DartifactId=aws-sns-sink \
 -Dkamelet-name=aws-sns \
 -Dcomponent-name=aws2-sns
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.046 s
[INFO] Finished at: 2024-11-27T11:50:40+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/matzew/go/src/knative.dev/eventing-integrations/aws-sns-sink). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

```

**Comment by christophd** [comment]
the archetype has been renamed from `kn-connector-archetype-sink` to `connector-archetype-sink`. I have updated the README in #38

**Comment by christophd** [comment]
Also, I have added the `-DoutputDirectory=integration-sink` parameter to the mvn archetype command. With this `outputDirectory` option you are able to run the command in the project root folder and the pom.xml will not get polluted with all that noise.

You just need to move the generated project then to the root project folder

**Comment by matzew** [comment]
I used the `sink` archetype, like:

```
mvn archetype:generate \
 -DarchetypeGroupId=dev.knative.eventing \
 -DarchetypeArtifactId=connector-archetype-sink \
 -DarchetypeVersion=1.0-SNAPSHOT \
 -DartifactId=aws-sns-sink \
 -Dkamelet-name=aws-sns \
 -Dcomponent-name=aws2-sns \
 -DoutputDirectory=aws-sns-sink

```

and it seems to lack the `properties.yaml` file, and the the `.adoc` file seems to be empty:

* https://github.com/matzew/eventing-integrations/blob/add_aws_sns_sink/aws-sns-sink/properties.adoc

**Comment by christophd** [comment]
yes, these files are filled with content when doing a first `mvn package` for this new module

**Comment by christophd** [comment]
you may need to add the new module to the root pom.xml in `modules` section so it gets built with the project

**Comment by matzew** [comment]
/close

thanks! The referenced PR fixed my issues
