### ISSUE TITLE
Push not to local registy

### ISSUE THREAD

**Issue by matzew** [knative-extensions/eventing-integrations#6]
Currently the build is configured in the `pom.xml` that it pushes to a local registry:
https://github.com/knative-extensions/eventing-integrations/blob/main/pom.xml#L28-L29

However for other java dataplane bits we have adjusted the build process. For instance:
* https://github.com/knative-extensions/eventing-kafka-broker/blob/b9233feecbfdadb1c4a584d3e9925cc117b2427c/hack/data-plane.sh#L59

**Comment by christophd** [comment]
You can overwrite the properties value with `-Dquarkus.container-image.registry=...` on a Maven build. For instance when pushing this to an official repository as part of the CI jobs during a release.

The local repository is handy for local testing where you push images to Kind cluster for instance.

**Comment by dsimansk** [comment]
/asign 

I'll take a look on CI setup required for that, and update the issue with my findings.
